// @@ object for set dynamic path for routing
export const pathData = {
  login: "/login",
  forgotPassword: "/forgotpass",
  otp: "/otp",
  createPassword: "/createpassword",
  dashboard: "/",
  applicationManagement: "/application-management",
  privacyPolicy: "/content-privacy-policy",
  termsAndCondition: "/content-terms-and-conditions",
  aboutUs: "/content-about-us",
  bannersManagement: "/banners-management",
  contentPublication: "/content-publication",
  contentFaq: "/content-faq",
  userManagement: "/user-management",
  userManagementCreateUser: "/user-management/createuser",
  userManagementUpdateUser: "/user-management/updateuser/",
  createBanner: "/banners-management/create-banner",
  updateBanner: "/banners-management/update-banner/",
  userMgmtUsersDetail: "/user-management/user-detail/",
  supportChat: "/support-chat",
  supportTicket: "/support-ticket",
  supportTicketDetails: "/support-ticket-details/",
  contentCreatePublication: "/content-publication/create",
  contentUpdatePublication: "/content-publication/update/",
  contentDetailPublication: "/content-publication/detail/",
  contentCreateFaq: "/content-faq/create",
  contentUpdateFaq: "/content-faq/update/",
  contentDetailFaq: "/content-faq/detail/",
  applicationDetail: "/application-management/detail/",
  profile: "/profile",
  editProfile: "/edit-profile",
  payments: "/payments",
  paymentDetails: "/payment-details",
  tradeMarks: "/trade-marks",
  tradeMarkDetails: "/trade-marks-details/",
};
